CHANNEL_ID:
GITHUB_TEAM_SLUG:
GITHUB_WEBHOOK_SECRET:
GITHUB_ORG:
REPO:
OKTA_TOKEN:
OKTA_URL: https:// ORG .okta.com/api/v1/groups/ GROUPID /users
SLACK_TOKEN:
GH_APP_INSTALL_ID: 
GITHUB_APP_ID: 
GITHUB_JWT_PEM_KEY: 
DOMAIN: