CHANNEL_ID: the Slack channel ID
GITHUB_TEAM_SLUG: The GitHub team handling your repo (the most common assignees)
GITHUB_WEBHOOK_SECRET: Your webhook secret
ORG: The GitHub org owner name
REPO: Repo name
OKTA_TOKEN: API token from Okta
OKTA_URL: https:// ORG .okta.com/api/v1/groups/ GROUPID /users
SLACK_TOKEN: API token from Slack
PROJECT_ID: GCP project name
GH_APP_INSTALL_ID: Your GitHub app install ID
GITHUB_APP_ID:  Your GitHub app ID
GITHUB_JWT_PEM_KEY: The JWT .pem key
DOMAIN: The domain after @ in your email address
ASSIGNEE_EMAILS: >
  If wanted, use these email addresses to look up Slack IDs for. user: email structure, one per line.
